/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExtensionSignRouteImport } from './routes/extension.sign'
import { Route as ExtensionPairRouteImport } from './routes/extension.pair'

const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionSignRoute = ExtensionSignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => ExtensionRoute,
} as any)
const ExtensionPairRoute = ExtensionPairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => ExtensionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extension': typeof ExtensionRouteWithChildren
  '/extension/pair': typeof ExtensionPairRoute
  '/extension/sign': typeof ExtensionSignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/extension': typeof ExtensionRouteWithChildren
  '/extension/pair': typeof ExtensionPairRoute
  '/extension/sign': typeof ExtensionSignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/extension': typeof ExtensionRouteWithChildren
  '/extension/pair': typeof ExtensionPairRoute
  '/extension/sign': typeof ExtensionSignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/extension' | '/extension/pair' | '/extension/sign'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/extension' | '/extension/pair' | '/extension/sign'
  id: '__root__' | '/' | '/extension' | '/extension/pair' | '/extension/sign'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExtensionRoute: typeof ExtensionRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension/sign': {
      id: '/extension/sign'
      path: '/sign'
      fullPath: '/extension/sign'
      preLoaderRoute: typeof ExtensionSignRouteImport
      parentRoute: typeof ExtensionRoute
    }
    '/extension/pair': {
      id: '/extension/pair'
      path: '/pair'
      fullPath: '/extension/pair'
      preLoaderRoute: typeof ExtensionPairRouteImport
      parentRoute: typeof ExtensionRoute
    }
  }
}

interface ExtensionRouteChildren {
  ExtensionPairRoute: typeof ExtensionPairRoute
  ExtensionSignRoute: typeof ExtensionSignRoute
}

const ExtensionRouteChildren: ExtensionRouteChildren = {
  ExtensionPairRoute: ExtensionPairRoute,
  ExtensionSignRoute: ExtensionSignRoute,
}

const ExtensionRouteWithChildren = ExtensionRoute._addFileChildren(
  ExtensionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExtensionRoute: ExtensionRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
