/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletIndexRouteImport } from './routes/wallet.index'
import { Route as ExtensionIndexRouteImport } from './routes/extension.index'
import { Route as WalletSignRouteImport } from './routes/wallet.sign'
import { Route as WalletSettingsRouteImport } from './routes/wallet.settings'
import { Route as WalletSecurityRouteImport } from './routes/wallet.security'
import { Route as WalletMultisendRouteImport } from './routes/wallet.multisend'
import { Route as WalletContactsRouteImport } from './routes/wallet.contacts'
import { Route as ExtensionSignRouteImport } from './routes/extension.sign'
import { Route as ExtensionPairRouteImport } from './routes/extension.pair'
import { Route as WalletChainXpubRouteImport } from './routes/wallet.$chain.xpub'
import { Route as WalletChainSweepRouteImport } from './routes/wallet.$chain.sweep'
import { Route as WalletChainSwapRouteImport } from './routes/wallet.$chain.swap'
import { Route as WalletChainSendRouteImport } from './routes/wallet.$chain.send'
import { Route as WalletChainReceiveRouteImport } from './routes/wallet.$chain.receive'
import { Route as WalletChainQrLoginRouteImport } from './routes/wallet.$chain.qr-login'
import { Route as WalletChainHistoryRouteImport } from './routes/wallet.$chain.history'
import { Route as WalletChainConsolidateRouteImport } from './routes/wallet.$chain.consolidate'
import { Route as ApiPublicRpcAlchemyChainRouteImport } from './routes/api.public.rpc.alchemy.$chain'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WalletRoute,
} as any)
const ExtensionIndexRoute = ExtensionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExtensionRoute,
} as any)
const WalletSignRoute = WalletSignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => WalletRoute,
} as any)
const WalletSettingsRoute = WalletSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WalletRoute,
} as any)
const WalletSecurityRoute = WalletSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => WalletRoute,
} as any)
const WalletMultisendRoute = WalletMultisendRouteImport.update({
  id: '/multisend',
  path: '/multisend',
  getParentRoute: () => WalletRoute,
} as any)
const WalletContactsRoute = WalletContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => WalletRoute,
} as any)
const ExtensionSignRoute = ExtensionSignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => ExtensionRoute,
} as any)
const ExtensionPairRoute = ExtensionPairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => ExtensionRoute,
} as any)
const WalletChainXpubRoute = WalletChainXpubRouteImport.update({
  id: '/$chain/xpub',
  path: '/$chain/xpub',
  getParentRoute: () => WalletRoute,
} as any)
const WalletChainSweepRoute = WalletChainSweepRouteImport.update({
  id: '/$chain/sweep',
  path: '/$chain/sweep',
  getParentRoute: () => WalletRoute,
} as any)
const WalletChainSwapRoute = WalletChainSwapRouteImport.update({
  id: '/$chain/swap',
  path: '/$chain/swap',
  getParentRoute: () => WalletRoute,
} as any)
const WalletChainSendRoute = WalletChainSendRouteImport.update({
  id: '/$chain/send',
  path: '/$chain/send',
  getParentRoute: () => WalletRoute,
} as any)
const WalletChainReceiveRoute = WalletChainReceiveRouteImport.update({
  id: '/$chain/receive',
  path: '/$chain/receive',
  getParentRoute: () => WalletRoute,
} as any)
const WalletChainQrLoginRoute = WalletChainQrLoginRouteImport.update({
  id: '/$chain/qr-login',
  path: '/$chain/qr-login',
  getParentRoute: () => WalletRoute,
} as any)
const WalletChainHistoryRoute = WalletChainHistoryRouteImport.update({
  id: '/$chain/history',
  path: '/$chain/history',
  getParentRoute: () => WalletRoute,
} as any)
const WalletChainConsolidateRoute = WalletChainConsolidateRouteImport.update({
  id: '/$chain/consolidate',
  path: '/$chain/consolidate',
  getParentRoute: () => WalletRoute,
} as any)
const ApiPublicRpcAlchemyChainRoute =
  ApiPublicRpcAlchemyChainRouteImport.update({
    id: '/api/public/rpc/alchemy/$chain',
    path: '/api/public/rpc/alchemy/$chain',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extension': typeof ExtensionRouteWithChildren
  '/manifesto': typeof ManifestoRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/extension/pair': typeof ExtensionPairRoute
  '/extension/sign': typeof ExtensionSignRoute
  '/wallet/contacts': typeof WalletContactsRoute
  '/wallet/multisend': typeof WalletMultisendRoute
  '/wallet/security': typeof WalletSecurityRoute
  '/wallet/settings': typeof WalletSettingsRoute
  '/wallet/sign': typeof WalletSignRoute
  '/extension/': typeof ExtensionIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/wallet/$chain/consolidate': typeof WalletChainConsolidateRoute
  '/wallet/$chain/history': typeof WalletChainHistoryRoute
  '/wallet/$chain/qr-login': typeof WalletChainQrLoginRoute
  '/wallet/$chain/receive': typeof WalletChainReceiveRoute
  '/wallet/$chain/send': typeof WalletChainSendRoute
  '/wallet/$chain/swap': typeof WalletChainSwapRoute
  '/wallet/$chain/sweep': typeof WalletChainSweepRoute
  '/wallet/$chain/xpub': typeof WalletChainXpubRoute
  '/api/public/rpc/alchemy/$chain': typeof ApiPublicRpcAlchemyChainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manifesto': typeof ManifestoRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/extension/pair': typeof ExtensionPairRoute
  '/extension/sign': typeof ExtensionSignRoute
  '/wallet/contacts': typeof WalletContactsRoute
  '/wallet/multisend': typeof WalletMultisendRoute
  '/wallet/security': typeof WalletSecurityRoute
  '/wallet/settings': typeof WalletSettingsRoute
  '/wallet/sign': typeof WalletSignRoute
  '/extension': typeof ExtensionIndexRoute
  '/wallet': typeof WalletIndexRoute
  '/wallet/$chain/consolidate': typeof WalletChainConsolidateRoute
  '/wallet/$chain/history': typeof WalletChainHistoryRoute
  '/wallet/$chain/qr-login': typeof WalletChainQrLoginRoute
  '/wallet/$chain/receive': typeof WalletChainReceiveRoute
  '/wallet/$chain/send': typeof WalletChainSendRoute
  '/wallet/$chain/swap': typeof WalletChainSwapRoute
  '/wallet/$chain/sweep': typeof WalletChainSweepRoute
  '/wallet/$chain/xpub': typeof WalletChainXpubRoute
  '/api/public/rpc/alchemy/$chain': typeof ApiPublicRpcAlchemyChainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/extension': typeof ExtensionRouteWithChildren
  '/manifesto': typeof ManifestoRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/extension/pair': typeof ExtensionPairRoute
  '/extension/sign': typeof ExtensionSignRoute
  '/wallet/contacts': typeof WalletContactsRoute
  '/wallet/multisend': typeof WalletMultisendRoute
  '/wallet/security': typeof WalletSecurityRoute
  '/wallet/settings': typeof WalletSettingsRoute
  '/wallet/sign': typeof WalletSignRoute
  '/extension/': typeof ExtensionIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/wallet/$chain/consolidate': typeof WalletChainConsolidateRoute
  '/wallet/$chain/history': typeof WalletChainHistoryRoute
  '/wallet/$chain/qr-login': typeof WalletChainQrLoginRoute
  '/wallet/$chain/receive': typeof WalletChainReceiveRoute
  '/wallet/$chain/send': typeof WalletChainSendRoute
  '/wallet/$chain/swap': typeof WalletChainSwapRoute
  '/wallet/$chain/sweep': typeof WalletChainSweepRoute
  '/wallet/$chain/xpub': typeof WalletChainXpubRoute
  '/api/public/rpc/alchemy/$chain': typeof ApiPublicRpcAlchemyChainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/extension'
    | '/manifesto'
    | '/privacy'
    | '/terms'
    | '/wallet'
    | '/extension/pair'
    | '/extension/sign'
    | '/wallet/contacts'
    | '/wallet/multisend'
    | '/wallet/security'
    | '/wallet/settings'
    | '/wallet/sign'
    | '/extension/'
    | '/wallet/'
    | '/wallet/$chain/consolidate'
    | '/wallet/$chain/history'
    | '/wallet/$chain/qr-login'
    | '/wallet/$chain/receive'
    | '/wallet/$chain/send'
    | '/wallet/$chain/swap'
    | '/wallet/$chain/sweep'
    | '/wallet/$chain/xpub'
    | '/api/public/rpc/alchemy/$chain'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manifesto'
    | '/privacy'
    | '/terms'
    | '/extension/pair'
    | '/extension/sign'
    | '/wallet/contacts'
    | '/wallet/multisend'
    | '/wallet/security'
    | '/wallet/settings'
    | '/wallet/sign'
    | '/extension'
    | '/wallet'
    | '/wallet/$chain/consolidate'
    | '/wallet/$chain/history'
    | '/wallet/$chain/qr-login'
    | '/wallet/$chain/receive'
    | '/wallet/$chain/send'
    | '/wallet/$chain/swap'
    | '/wallet/$chain/sweep'
    | '/wallet/$chain/xpub'
    | '/api/public/rpc/alchemy/$chain'
  id:
    | '__root__'
    | '/'
    | '/extension'
    | '/manifesto'
    | '/privacy'
    | '/terms'
    | '/wallet'
    | '/extension/pair'
    | '/extension/sign'
    | '/wallet/contacts'
    | '/wallet/multisend'
    | '/wallet/security'
    | '/wallet/settings'
    | '/wallet/sign'
    | '/extension/'
    | '/wallet/'
    | '/wallet/$chain/consolidate'
    | '/wallet/$chain/history'
    | '/wallet/$chain/qr-login'
    | '/wallet/$chain/receive'
    | '/wallet/$chain/send'
    | '/wallet/$chain/swap'
    | '/wallet/$chain/sweep'
    | '/wallet/$chain/xpub'
    | '/api/public/rpc/alchemy/$chain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExtensionRoute: typeof ExtensionRouteWithChildren
  ManifestoRoute: typeof ManifestoRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRouteWithChildren
  ApiPublicRpcAlchemyChainRoute: typeof ApiPublicRpcAlchemyChainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof WalletRoute
    }
    '/extension/': {
      id: '/extension/'
      path: '/'
      fullPath: '/extension/'
      preLoaderRoute: typeof ExtensionIndexRouteImport
      parentRoute: typeof ExtensionRoute
    }
    '/wallet/sign': {
      id: '/wallet/sign'
      path: '/sign'
      fullPath: '/wallet/sign'
      preLoaderRoute: typeof WalletSignRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/settings': {
      id: '/wallet/settings'
      path: '/settings'
      fullPath: '/wallet/settings'
      preLoaderRoute: typeof WalletSettingsRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/security': {
      id: '/wallet/security'
      path: '/security'
      fullPath: '/wallet/security'
      preLoaderRoute: typeof WalletSecurityRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/multisend': {
      id: '/wallet/multisend'
      path: '/multisend'
      fullPath: '/wallet/multisend'
      preLoaderRoute: typeof WalletMultisendRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/contacts': {
      id: '/wallet/contacts'
      path: '/contacts'
      fullPath: '/wallet/contacts'
      preLoaderRoute: typeof WalletContactsRouteImport
      parentRoute: typeof WalletRoute
    }
    '/extension/sign': {
      id: '/extension/sign'
      path: '/sign'
      fullPath: '/extension/sign'
      preLoaderRoute: typeof ExtensionSignRouteImport
      parentRoute: typeof ExtensionRoute
    }
    '/extension/pair': {
      id: '/extension/pair'
      path: '/pair'
      fullPath: '/extension/pair'
      preLoaderRoute: typeof ExtensionPairRouteImport
      parentRoute: typeof ExtensionRoute
    }
    '/wallet/$chain/xpub': {
      id: '/wallet/$chain/xpub'
      path: '/$chain/xpub'
      fullPath: '/wallet/$chain/xpub'
      preLoaderRoute: typeof WalletChainXpubRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/$chain/sweep': {
      id: '/wallet/$chain/sweep'
      path: '/$chain/sweep'
      fullPath: '/wallet/$chain/sweep'
      preLoaderRoute: typeof WalletChainSweepRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/$chain/swap': {
      id: '/wallet/$chain/swap'
      path: '/$chain/swap'
      fullPath: '/wallet/$chain/swap'
      preLoaderRoute: typeof WalletChainSwapRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/$chain/send': {
      id: '/wallet/$chain/send'
      path: '/$chain/send'
      fullPath: '/wallet/$chain/send'
      preLoaderRoute: typeof WalletChainSendRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/$chain/receive': {
      id: '/wallet/$chain/receive'
      path: '/$chain/receive'
      fullPath: '/wallet/$chain/receive'
      preLoaderRoute: typeof WalletChainReceiveRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/$chain/qr-login': {
      id: '/wallet/$chain/qr-login'
      path: '/$chain/qr-login'
      fullPath: '/wallet/$chain/qr-login'
      preLoaderRoute: typeof WalletChainQrLoginRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/$chain/history': {
      id: '/wallet/$chain/history'
      path: '/$chain/history'
      fullPath: '/wallet/$chain/history'
      preLoaderRoute: typeof WalletChainHistoryRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/$chain/consolidate': {
      id: '/wallet/$chain/consolidate'
      path: '/$chain/consolidate'
      fullPath: '/wallet/$chain/consolidate'
      preLoaderRoute: typeof WalletChainConsolidateRouteImport
      parentRoute: typeof WalletRoute
    }
    '/api/public/rpc/alchemy/$chain': {
      id: '/api/public/rpc/alchemy/$chain'
      path: '/api/public/rpc/alchemy/$chain'
      fullPath: '/api/public/rpc/alchemy/$chain'
      preLoaderRoute: typeof ApiPublicRpcAlchemyChainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExtensionRouteChildren {
  ExtensionPairRoute: typeof ExtensionPairRoute
  ExtensionSignRoute: typeof ExtensionSignRoute
  ExtensionIndexRoute: typeof ExtensionIndexRoute
}

const ExtensionRouteChildren: ExtensionRouteChildren = {
  ExtensionPairRoute: ExtensionPairRoute,
  ExtensionSignRoute: ExtensionSignRoute,
  ExtensionIndexRoute: ExtensionIndexRoute,
}

const ExtensionRouteWithChildren = ExtensionRoute._addFileChildren(
  ExtensionRouteChildren,
)

interface WalletRouteChildren {
  WalletContactsRoute: typeof WalletContactsRoute
  WalletMultisendRoute: typeof WalletMultisendRoute
  WalletSecurityRoute: typeof WalletSecurityRoute
  WalletSettingsRoute: typeof WalletSettingsRoute
  WalletSignRoute: typeof WalletSignRoute
  WalletIndexRoute: typeof WalletIndexRoute
  WalletChainConsolidateRoute: typeof WalletChainConsolidateRoute
  WalletChainHistoryRoute: typeof WalletChainHistoryRoute
  WalletChainQrLoginRoute: typeof WalletChainQrLoginRoute
  WalletChainReceiveRoute: typeof WalletChainReceiveRoute
  WalletChainSendRoute: typeof WalletChainSendRoute
  WalletChainSwapRoute: typeof WalletChainSwapRoute
  WalletChainSweepRoute: typeof WalletChainSweepRoute
  WalletChainXpubRoute: typeof WalletChainXpubRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletContactsRoute: WalletContactsRoute,
  WalletMultisendRoute: WalletMultisendRoute,
  WalletSecurityRoute: WalletSecurityRoute,
  WalletSettingsRoute: WalletSettingsRoute,
  WalletSignRoute: WalletSignRoute,
  WalletIndexRoute: WalletIndexRoute,
  WalletChainConsolidateRoute: WalletChainConsolidateRoute,
  WalletChainHistoryRoute: WalletChainHistoryRoute,
  WalletChainQrLoginRoute: WalletChainQrLoginRoute,
  WalletChainReceiveRoute: WalletChainReceiveRoute,
  WalletChainSendRoute: WalletChainSendRoute,
  WalletChainSwapRoute: WalletChainSwapRoute,
  WalletChainSweepRoute: WalletChainSweepRoute,
  WalletChainXpubRoute: WalletChainXpubRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExtensionRoute: ExtensionRouteWithChildren,
  ManifestoRoute: ManifestoRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRouteWithChildren,
  ApiPublicRpcAlchemyChainRoute: ApiPublicRpcAlchemyChainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
