/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExtensionIndexRouteImport } from './routes/extension.index'
import { Route as ExtensionSignRouteImport } from './routes/extension.sign'
import { Route as ExtensionPairRouteImport } from './routes/extension.pair'
import { Route as ApiPublicProbeRouteImport } from './routes/api.public.probe'
import { Route as ApiPublicRpcAlchemyChainRouteImport } from './routes/api.public.rpc.alchemy.$chain'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionIndexRoute = ExtensionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExtensionRoute,
} as any)
const ExtensionSignRoute = ExtensionSignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => ExtensionRoute,
} as any)
const ExtensionPairRoute = ExtensionPairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => ExtensionRoute,
} as any)
const ApiPublicProbeRoute = ApiPublicProbeRouteImport.update({
  id: '/api/public/probe',
  path: '/api/public/probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRpcAlchemyChainRoute =
  ApiPublicRpcAlchemyChainRouteImport.update({
    id: '/api/public/rpc/alchemy/$chain',
    path: '/api/public/rpc/alchemy/$chain',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extension': typeof ExtensionRouteWithChildren
  '/manifesto': typeof ManifestoRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/extension/pair': typeof ExtensionPairRoute
  '/extension/sign': typeof ExtensionSignRoute
  '/extension/': typeof ExtensionIndexRoute
  '/api/public/probe': typeof ApiPublicProbeRoute
  '/api/public/rpc/alchemy/$chain': typeof ApiPublicRpcAlchemyChainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manifesto': typeof ManifestoRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/extension/pair': typeof ExtensionPairRoute
  '/extension/sign': typeof ExtensionSignRoute
  '/extension': typeof ExtensionIndexRoute
  '/api/public/probe': typeof ApiPublicProbeRoute
  '/api/public/rpc/alchemy/$chain': typeof ApiPublicRpcAlchemyChainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/extension': typeof ExtensionRouteWithChildren
  '/manifesto': typeof ManifestoRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/extension/pair': typeof ExtensionPairRoute
  '/extension/sign': typeof ExtensionSignRoute
  '/extension/': typeof ExtensionIndexRoute
  '/api/public/probe': typeof ApiPublicProbeRoute
  '/api/public/rpc/alchemy/$chain': typeof ApiPublicRpcAlchemyChainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/extension'
    | '/manifesto'
    | '/privacy'
    | '/terms'
    | '/wallet'
    | '/extension/pair'
    | '/extension/sign'
    | '/extension/'
    | '/api/public/probe'
    | '/api/public/rpc/alchemy/$chain'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manifesto'
    | '/privacy'
    | '/terms'
    | '/wallet'
    | '/extension/pair'
    | '/extension/sign'
    | '/extension'
    | '/api/public/probe'
    | '/api/public/rpc/alchemy/$chain'
  id:
    | '__root__'
    | '/'
    | '/extension'
    | '/manifesto'
    | '/privacy'
    | '/terms'
    | '/wallet'
    | '/extension/pair'
    | '/extension/sign'
    | '/extension/'
    | '/api/public/probe'
    | '/api/public/rpc/alchemy/$chain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExtensionRoute: typeof ExtensionRouteWithChildren
  ManifestoRoute: typeof ManifestoRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRoute
  ApiPublicProbeRoute: typeof ApiPublicProbeRoute
  ApiPublicRpcAlchemyChainRoute: typeof ApiPublicRpcAlchemyChainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension/': {
      id: '/extension/'
      path: '/'
      fullPath: '/extension/'
      preLoaderRoute: typeof ExtensionIndexRouteImport
      parentRoute: typeof ExtensionRoute
    }
    '/extension/sign': {
      id: '/extension/sign'
      path: '/sign'
      fullPath: '/extension/sign'
      preLoaderRoute: typeof ExtensionSignRouteImport
      parentRoute: typeof ExtensionRoute
    }
    '/extension/pair': {
      id: '/extension/pair'
      path: '/pair'
      fullPath: '/extension/pair'
      preLoaderRoute: typeof ExtensionPairRouteImport
      parentRoute: typeof ExtensionRoute
    }
    '/api/public/probe': {
      id: '/api/public/probe'
      path: '/api/public/probe'
      fullPath: '/api/public/probe'
      preLoaderRoute: typeof ApiPublicProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rpc/alchemy/$chain': {
      id: '/api/public/rpc/alchemy/$chain'
      path: '/api/public/rpc/alchemy/$chain'
      fullPath: '/api/public/rpc/alchemy/$chain'
      preLoaderRoute: typeof ApiPublicRpcAlchemyChainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExtensionRouteChildren {
  ExtensionPairRoute: typeof ExtensionPairRoute
  ExtensionSignRoute: typeof ExtensionSignRoute
  ExtensionIndexRoute: typeof ExtensionIndexRoute
}

const ExtensionRouteChildren: ExtensionRouteChildren = {
  ExtensionPairRoute: ExtensionPairRoute,
  ExtensionSignRoute: ExtensionSignRoute,
  ExtensionIndexRoute: ExtensionIndexRoute,
}

const ExtensionRouteWithChildren = ExtensionRoute._addFileChildren(
  ExtensionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExtensionRoute: ExtensionRouteWithChildren,
  ManifestoRoute: ManifestoRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRoute,
  ApiPublicProbeRoute: ApiPublicProbeRoute,
  ApiPublicRpcAlchemyChainRoute: ApiPublicRpcAlchemyChainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
